name: ombapos
description: "Kasir Project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.2.0
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
